version: "2"
services:
  nginx-react:
    container_name: react-container-yarn-typescript-2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production