services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build   # <- usa o estágio "build" com Node
    ports:
      - "3000:3000"
    volumes:
      - .:/app/src
      - /app/node_modules
    command: yarn start --host 0.0.0.0  # ou npm start, se preferir
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    
     